// Paste only a short-lived token generated by `./gradlew generateDemoTokens` for local rehearsal.
// Never commit a real token. Production native apps use Authorization Code + PKCE and secure storage.
export const classroomToken = '';
